version: '3.8'

services:

  db:
    container_name: ol-intel-db
    build:
      context: ./services/datahub/src/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=ol_intel
      - POSTGRES_PASSWORD=ol_intel
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  crawler:
    container_name: ol-intel-crawler
    build: 
      context: ./services/datahub/src/crawler
      dockerfile: Dockerfile
    command: python /usr/src/app/project/app/main.py
    volumes:
      - ./services/datahub/src/crawler/:/usr/src/app/
    depends_on:
      - db
    env_file:
      - ./services/datahub/src/.env.dev

volumes:
  postgres_data: